name: black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone snek'
        uses: actions/checkout@v2
        with:
          path: snek

      - name: 'Build snek container'
        run: |
          docker build -t snek \
            -f snek/.github/Dockerfile-black \
            snek

      - name: 'Check snek/python code format'
        run: |
          docker run --rm \
            snek \
            make black
