name: snek

on: [push, pull_request]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ./
    - name: snek action step
      uses: ./action.yml
